# Minimal configuration values
namespace: krenek-ns
image:
  repository: cerit.io/adamondrejka/gromacs-tuner-api
  tag: "1.2"
ingress:
  host: "gromacs-tuner-ljocha.dyn.cloud.e-infra.cz"
  tlsSecretName: "gromacs-tuner-ljocha-dyn-cloud-e-infra-cz-tls"
