# Minimal configuration values
namespace: gromacs-tuner-ns
image:
  repository: cerit.io/adamondrejka/gromacs-tuner-api
  tag: "1.2"
ingress:
  host: "gromacs-tuner.dyn.cloud.e-infra.cz"
  tlsSecretName: "gromacs-tuner-dyn-cloud-e-infra-cz-tls"
auth:
  user: "admin"
  password: "strong-secret-here"