apiVersion: v1
kind: Service
metadata:
  name: gromacs-tuner-api-svc
  namespace: gromacs-tuner-ns
spec:
  selector:
    app: gromacs-tuner-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
