apiVersion: v1
kind: Service
metadata:
  name: gromacs-tuner-api-svc
spec:
  type: ClusterIP
  ports:
  - name: gromacs-tuner-api-port
    port: 8000
    targetPort: 8000
  selector:
    app: gromacs-tuner-api