# k8s/api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gromacs-tuner-api-ingress
  namespace: gromacs-tuner-ns
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "gromacs-tuner.dyn.cloud.e-infra.cz"
      secretName: gromacs-tuner-dyn-cloud-e-infra-cz-tls
  rules:
    - host: "gromacs-tuner.dyn.cloud.e-infra.cz"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gromacs-tuner-api-svc
                port:
                  number: 8000