apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tuner-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tuner-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tuner-api
    spec:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: RAY_ADDRESS
            value: "ray://{{ .Release.Name }}-raycluster-head-svc:10001"
          - name: TUNER_DB
            value: "/data/tuner.db"
          - name: TUNER_USER
            valueFrom:
              secretKeyRef:
                name: tuner-auth
                key: user
          - name: TUNER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tuner-auth
                key: password
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: {{ .Values.api.resources.limits.cpu }}
            memory: {{ .Values.api.resources.limits.memory }}
          requests:
            cpu: {{ .Values.api.resources.requests.cpu }}
            memory: {{ .Values.api.resources.requests.memory }}
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: gromacs-pvc
          mountPath: /tmp/tpr
        - name: gromacs-pvc
          mountPath: /data
      volumes:
      - name: gromacs-pvc
        persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tuner-pvc
