apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: raycluster-complete
  namespace: {{ .Values.namespace }}
spec:
  rayVersion: '2.42.1'
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
      num-cpus: '0'
    template:
      metadata:
        labels: {}
      spec:
        containers:
        - name: ray-head
          image: cerit.io/adamondrejka/gmx-cuda-ray-2-42-1-with-user
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
            - mountPath: /tmp/tpr
              name: gromacs-pvc
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
        volumes:
          - name: ray-logs
            emptyDir: {}
          - name: gromacs-pvc
            persistentVolumeClaim:
              claimName: gromacs-pvc
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 8
    groupName: gromacs-group
    rayStartParams:
      num-cpus: '8'
      num-gpus: '1'
    template:
      spec:
        nodeSelector: # Explicitly asking for A40 as it is most available
          nvidia.com/gpu.product: 'NVIDIA-A40'
        containers:
        - name: ray-worker
          image: cerit.io/adamondrejka/gmx-cuda-ray-2-42-1-with-user
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
            - mountPath: /tmp/tpr
              name: gromacs-pvc
          resources:
            limits:
              cpu: "10"
              memory: "24Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: "4Gi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
        volumes:
          - name: ray-logs
            emptyDir: {}
          - name: gromacs-pvc
            persistentVolumeClaim:
              claimName: gromacs-pvc
