apiVersion: v1
kind: Secret
metadata:
  name: tuner-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: {{ .Values.auth.user | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
